// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string word = 1;</code>
   * @return Whether the word field is set.
   */
  boolean hasWord();
  /**
   * <code>optional string word = 1;</code>
   * @return The word.
   */
  java.lang.String getWord();
  /**
   * <code>optional string word = 1;</code>
   * @return The bytes for word.
   */
  com.google.protobuf.ByteString
      getWordBytes();

  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @return A list containing the vectorClock.
   */
  java.util.List<java.lang.Integer> getVectorClockList();
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @return The count of vectorClock.
   */
  int getVectorClockCount();
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @param index The index of the element to return.
   * @return The vectorClock at the given index.
   */
  int getVectorClock(int index);
}
