// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

/**
 * Protobuf type {@code Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    word_ = "";
    vectorClock_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageOuterClass.internal_static_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageOuterClass.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Message.class, Message.Builder.class);
  }

  private int bitField0_;
  public static final int WORD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object word_ = "";
  /**
   * <code>optional string word = 1;</code>
   * @return Whether the word field is set.
   */
  @java.lang.Override
  public boolean hasWord() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string word = 1;</code>
   * @return The word.
   */
  @java.lang.Override
  public java.lang.String getWord() {
    java.lang.Object ref = word_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      word_ = s;
      return s;
    }
  }
  /**
   * <code>optional string word = 1;</code>
   * @return The bytes for word.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWordBytes() {
    java.lang.Object ref = word_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      word_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VECTORCLOCK_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList vectorClock_;
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @return A list containing the vectorClock.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getVectorClockList() {
    return vectorClock_;
  }
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @return The count of vectorClock.
   */
  public int getVectorClockCount() {
    return vectorClock_.size();
  }
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @param index The index of the element to return.
   * @return The vectorClock at the given index.
   */
  public int getVectorClock(int index) {
    return vectorClock_.getInt(index);
  }
  private int vectorClockMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, word_);
    }
    if (getVectorClockList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(vectorClockMemoizedSerializedSize);
    }
    for (int i = 0; i < vectorClock_.size(); i++) {
      output.writeInt32NoTag(vectorClock_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, word_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < vectorClock_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(vectorClock_.getInt(i));
      }
      size += dataSize;
      if (!getVectorClockList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      vectorClockMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Message)) {
      return super.equals(obj);
    }
    Message other = (Message) obj;

    if (hasWord() != other.hasWord()) return false;
    if (hasWord()) {
      if (!getWord()
          .equals(other.getWord())) return false;
    }
    if (!getVectorClockList()
        .equals(other.getVectorClockList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWord()) {
      hash = (37 * hash) + WORD_FIELD_NUMBER;
      hash = (53 * hash) + getWord().hashCode();
    }
    if (getVectorClockCount() > 0) {
      hash = (37 * hash) + VECTORCLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getVectorClockList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Message.Builder.class);
    }

    // Construct using Message.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      word_ = "";
      vectorClock_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageOuterClass.internal_static_Message_descriptor;
    }

    @java.lang.Override
    public Message getDefaultInstanceForType() {
      return Message.getDefaultInstance();
    }

    @java.lang.Override
    public Message build() {
      Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Message buildPartial() {
      Message result = new Message(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(Message result) {
      if (((bitField0_ & 0x00000002) != 0)) {
        vectorClock_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.vectorClock_ = vectorClock_;
    }

    private void buildPartial0(Message result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.word_ = word_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Message) {
        return mergeFrom((Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Message other) {
      if (other == Message.getDefaultInstance()) return this;
      if (other.hasWord()) {
        word_ = other.word_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.vectorClock_.isEmpty()) {
        if (vectorClock_.isEmpty()) {
          vectorClock_ = other.vectorClock_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureVectorClockIsMutable();
          vectorClock_.addAll(other.vectorClock_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              word_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              int v = input.readInt32();
              ensureVectorClockIsMutable();
              vectorClock_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureVectorClockIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                vectorClock_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object word_ = "";
    /**
     * <code>optional string word = 1;</code>
     * @return Whether the word field is set.
     */
    public boolean hasWord() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string word = 1;</code>
     * @return The word.
     */
    public java.lang.String getWord() {
      java.lang.Object ref = word_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        word_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string word = 1;</code>
     * @return The bytes for word.
     */
    public com.google.protobuf.ByteString
        getWordBytes() {
      java.lang.Object ref = word_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        word_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string word = 1;</code>
     * @param value The word to set.
     * @return This builder for chaining.
     */
    public Builder setWord(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      word_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string word = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWord() {
      word_ = getDefaultInstance().getWord();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string word = 1;</code>
     * @param value The bytes for word to set.
     * @return This builder for chaining.
     */
    public Builder setWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      word_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList vectorClock_ = emptyIntList();
    private void ensureVectorClockIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        vectorClock_ = mutableCopy(vectorClock_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @return A list containing the vectorClock.
     */
    public java.util.List<java.lang.Integer>
        getVectorClockList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(vectorClock_) : vectorClock_;
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @return The count of vectorClock.
     */
    public int getVectorClockCount() {
      return vectorClock_.size();
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @param index The index of the element to return.
     * @return The vectorClock at the given index.
     */
    public int getVectorClock(int index) {
      return vectorClock_.getInt(index);
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @param index The index to set the value at.
     * @param value The vectorClock to set.
     * @return This builder for chaining.
     */
    public Builder setVectorClock(
        int index, int value) {
      
      ensureVectorClockIsMutable();
      vectorClock_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @param value The vectorClock to add.
     * @return This builder for chaining.
     */
    public Builder addVectorClock(int value) {
      
      ensureVectorClockIsMutable();
      vectorClock_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @param values The vectorClock to add.
     * @return This builder for chaining.
     */
    public Builder addAllVectorClock(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureVectorClockIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, vectorClock_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 vectorClock = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVectorClock() {
      vectorClock_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Message();
  }

  public static Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

